name: selim_trade
description: Application for sale gates
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  auto_route: ^5.0.4
  flutter_svg: ^2.0.0+1
  injectable: ^2.1.0
  intl: ^0.17.0
  easy_localization: ^3.0.1
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.9
  google_maps_flutter: ^2.2.3
  carousel_slider: ^4.2.1
  dart_code_metrics: ^5.5.1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.19
  shimmer: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.4
flutter_native_splash: 
 color: '#105BFB'
 image:   assets/images/logo.png
 ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/mainbackground.png
    - assets/images/dialogback.png
    - assets/l10n/

  

  

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  